
// repos actions  types

//Fetching
export const FETCHING_REPOS="FETCHING_REPOS"
export const FETCHING_REPOS_SUCCESS = "FETCHING_REPOS_SUCCESS"
export const FETCHING_REPOS_FAILURE = "FETCHING_REPOS_FAILURE"

//Refreshing
export const REFRESH_REPOS="REFRESH_REPOS"
export const REFRESH_REPOS_SUCCESS = "REFRESH_REPOS_SUCCESS"
export const REFRESH_REPOS_FAILURE = "REFRESH_REPOS_FAILURE"

